# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zlCCqqw3CSKorSDPV9DmGoMKQeubpIyv
"""

# ==========================================================
# Name: Your Name
# Course: MSDS-532 Data Science Programming with Python
# Lab Assignment: Regression Techniques and Regularization
# ==========================================================

# Import Libraries
import os
import zipfile
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# ==========================================================
# STEP 1: LOAD ZIP DATASET (Google Colab)
# ==========================================================

# Find uploaded ZIP file
zip_files = [f for f in os.listdir() if f.endswith(".zip")]

if len(zip_files) == 0:
    raise FileNotFoundError("No ZIP file found. Please upload your dataset ZIP.")

zip_file = zip_files[0]
print("ZIP File Found:", zip_file)

# Extract ZIP
with zipfile.ZipFile(zip_file, 'r') as zip_ref:
    zip_ref.extractall()

# Find dataset file
dataset = None

for root, dirs, files in os.walk("."):
    for file in files:
        if file.endswith(".txt") and "diabetes" in file.lower():
            dataset = os.path.join(root, file)

if dataset is None:
    raise FileNotFoundError("diabetes.tab.txt not found.")

print("Dataset Loaded:", dataset)

# Read Dataset
df = pd.read_csv(dataset, sep="\t")

print("\nFirst Five Records")
print(df.head())

print("\nShape:", df.shape)

print("\nDataset Info")
print(df.info())

print("\nSummary Statistics")
print(df.describe())

print("\nMissing Values")
print(df.isnull().sum())

# Target Distribution
plt.figure(figsize=(7,5))
plt.hist(df["Y"], bins=20, edgecolor="black")
plt.title("Distribution of Target Variable")
plt.xlabel("Target")
plt.ylabel("Frequency")
plt.show()

# ==========================================================
# SIMPLE LINEAR REGRESSION
# ==========================================================

X_simple = df[["BMI"]]
y_simple = df["Y"]

X_train_s, X_test_s, y_train_s, y_test_s = train_test_split(
    X_simple, y_simple, test_size=0.2, random_state=42
)

simple_model = LinearRegression()
simple_model.fit(X_train_s, y_train_s)

simple_pred = simple_model.predict(X_test_s)

simple_mae = mean_absolute_error(y_test_s, simple_pred)
simple_mse = mean_squared_error(y_test_s, simple_pred)
simple_rmse = np.sqrt(simple_mse)
simple_r2 = r2_score(y_test_s, simple_pred)

print("\nSimple Linear Regression")
print("MAE :", simple_mae)
print("MSE :", simple_mse)
print("RMSE:", simple_rmse)
print("R²  :", simple_r2)

plt.figure(figsize=(7,5))
plt.scatter(X_test_s, y_test_s)
plt.plot(X_test_s, simple_pred, color="red")
plt.title("Simple Linear Regression")
plt.xlabel("BMI")
plt.ylabel("Target")
plt.show()

# ==========================================================
# MULTIPLE LINEAR REGRESSION
# ==========================================================

X = df.drop("Y", axis=1)
y = df["Y"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

multiple_model = LinearRegression()
multiple_model.fit(X_train, y_train)

multiple_pred = multiple_model.predict(X_test)

multiple_mae = mean_absolute_error(y_test, multiple_pred)
multiple_mse = mean_squared_error(y_test, multiple_pred)
multiple_rmse = np.sqrt(multiple_mse)
multiple_r2 = r2_score(y_test, multiple_pred)

print("\nMultiple Linear Regression")
print("MAE :", multiple_mae)
print("MSE :", multiple_mse)
print("RMSE:", multiple_rmse)
print("R²  :", multiple_r2)

plt.figure(figsize=(6,6))
plt.scatter(y_test, multiple_pred)
plt.plot([y_test.min(), y_test.max()],
         [y_test.min(), y_test.max()],
         color="red")
plt.xlabel("Actual")
plt.ylabel("Predicted")
plt.title("Multiple Regression")
plt.show()

# ==========================================================
# POLYNOMIAL REGRESSION
# ==========================================================

poly_results = {}

for degree in [2,3]:

    poly_model = Pipeline([
        ("poly", PolynomialFeatures(degree)),
        ("linear", LinearRegression())
    ])

    poly_model.fit(X_train_s, y_train_s)

    poly_pred = poly_model.predict(X_test_s)

    mae = mean_absolute_error(y_test_s, poly_pred)
    mse = mean_squared_error(y_test_s, poly_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_test_s, poly_pred)

    poly_results[degree] = [mae,mse,rmse,r2]

    print("\nPolynomial Degree", degree)
    print("MAE :", mae)
    print("MSE :", mse)
    print("RMSE:", rmse)
    print("R²  :", r2)

    plt.figure(figsize=(7,5))
    plt.scatter(X_test_s["BMI"], y_test_s)

    order = np.argsort(X_test_s["BMI"])

    plt.plot(
        X_test_s["BMI"].values[order],
        poly_pred[order],
        color="red"
    )

    plt.title(f"Polynomial Regression Degree {degree}")
    plt.xlabel("BMI")
    plt.ylabel("Target")
    plt.show()

# ==========================================================
# RIDGE REGRESSION
# ==========================================================

ridge = Ridge(alpha=1.0)
ridge.fit(X_train,y_train)

ridge_pred = ridge.predict(X_test)

ridge_mae = mean_absolute_error(y_test,ridge_pred)
ridge_mse = mean_squared_error(y_test,ridge_pred)
ridge_rmse = np.sqrt(ridge_mse)
ridge_r2 = r2_score(y_test,ridge_pred)

print("\nRidge Regression")
print("MAE :", ridge_mae)
print("MSE :", ridge_mse)
print("RMSE:", ridge_rmse)
print("R²  :", ridge_r2)

plt.figure(figsize=(6,6))
plt.scatter(y_test,ridge_pred)
plt.plot([y_test.min(),y_test.max()],
         [y_test.min(),y_test.max()],
         color="red")
plt.title("Ridge Regression")
plt.show()

# ==========================================================
# LASSO REGRESSION
# ==========================================================

lasso = Lasso(alpha=0.1)
lasso.fit(X_train,y_train)

lasso_pred = lasso.predict(X_test)

lasso_mae = mean_absolute_error(y_test,lasso_pred)
lasso_mse = mean_squared_error(y_test,lasso_pred)
lasso_rmse = np.sqrt(lasso_mse)
lasso_r2 = r2_score(y_test,lasso_pred)

print("\nLasso Regression")
print("MAE :", lasso_mae)
print("MSE :", lasso_mse)
print("RMSE:", lasso_rmse)
print("R²  :", lasso_r2)

plt.figure(figsize=(6,6))
plt.scatter(y_test,lasso_pred)
plt.plot([y_test.min(),y_test.max()],
         [y_test.min(),y_test.max()],
         color="red")
plt.title("Lasso Regression")
plt.show()

# ==========================================================
# ALPHA COMPARISON
# ==========================================================

print("\nRidge Alpha Comparison")

alphas=[0.01,0.1,1,10]

for a in alphas:
    model=Ridge(alpha=a)
    model.fit(X_train,y_train)
    pred=model.predict(X_test)
    print("Alpha:",a,"R²:",round(r2_score(y_test,pred),4))

print("\nLasso Alpha Comparison")

for a in alphas:
    model=Lasso(alpha=a)
    model.fit(X_train,y_train)
    pred=model.predict(X_test)
    print("Alpha:",a,"R²:",round(r2_score(y_test,pred),4))

# ==========================================================
# MODEL COMPARISON
# ==========================================================

results=pd.DataFrame({
    "Model":[
        "Simple Linear",
        "Multiple Linear",
        "Polynomial Degree 2",
        "Polynomial Degree 3",
        "Ridge",
        "Lasso"
    ],
    "MAE":[
        simple_mae,
        multiple_mae,
        poly_results[2][0],
        poly_results[3][0],
        ridge_mae,
        lasso_mae
    ],
    "MSE":[
        simple_mse,
        multiple_mse,
        poly_results[2][1],
        poly_results[3][1],
        ridge_mse,
        lasso_mse
    ],
    "RMSE":[
        simple_rmse,
        multiple_rmse,
        poly_results[2][2],
        poly_results[3][2],
        ridge_rmse,
        lasso_rmse
    ],
    "R2":[
        simple_r2,
        multiple_r2,
        poly_results[2][3],
        poly_results[3][3],
        ridge_r2,
        lasso_r2
    ]
})

print("\nModel Comparison")
print(results)

plt.figure(figsize=(10,5))
plt.bar(results["Model"],results["R2"])
plt.title("Regression Model Comparison")
plt.xlabel("Models")
plt.ylabel("R² Score")
plt.xticks(rotation=20)
plt.show()

print("\nObservations")
print("""
1. Simple Linear Regression uses only BMI.
2. Multiple Regression generally provides better accuracy.
3. Polynomial Regression captures nonlinear relationships.
4. Ridge Regression reduces overfitting using L2 regularization.
5. Lasso Regression performs feature selection using L1 regularization.
6. Larger alpha values increase regularization strength.
7. Compare MAE, MSE, RMSE and R² to identify the best model.
""")